# write_docs_full.ps1 — Genera README.md y CHANGELOG.md (UTF-8) sin here-strings
$ErrorActionPreference = 'Stop'
Set-Location 'C:\gestor-reparaciones\apps\web'

# ------- README.md -------
$readme = @(
'# Gestor de Reparaciones — BricoFrank'
''
'SPA de taller con **React + TypeScript + Vite**, persistencia local en **IndexedDB (Dexie)** y UI con **Tailwind**. Pensada para funcionar sin red y reanudarse al volver al navegador.'
''
'## Características'
'- **Registro** de cliente con **múltiples equipos** por alta. Categorías incluyen **Baterías**.'
'- **Órdenes**: búsqueda, filtros (estado/fecha), ordenación, **Exportar CSV** e **Importar JSON**.'
'- **Presupuesto**: cálculo de mano de obra y piezas **sin IVA**.'
'- **Reparación**: costes, presets de tarifa, atajos de horas, timeline con **plantillas**, piezas, **adjuntos**, **edición** de datos, **Exportar JSON** e **Imprimir**.'
''
'## Requisitos'
'- Node 18+ (recomendado 20+)'
'- npm 9+'
''
'## Instalación y arranque'
'```bash'
'npm install'
'npm run dev'
'```'
''
'## Scripts'
'- `npm run dev` — desarrollo'
'- `npm run build` — producción'
'- `npm run preview` — previsualización del build'
''
'## Estructura'
'```'
'apps/web/'
'  index.html'
'  package.json'
'  postcss.config.js'
'  src/'
'    App.tsx'
'    styles.css'
'    data/db.ts'
'    domain/types.ts'
'    modules/'
'      app/Layout.tsx'
'      registro/Registro.tsx'
'      ordenes/Ordenes.tsx'
'      presupuesto/Presupuesto.tsx'
'      reparacion/DetalleOrden.tsx'
'```'
''
'## Modelo de datos (Dexie)'
'- clientes: id, nombre, telefono, email?, fecha_alta'
'- equipos: id, clienteId, categoria, marca, modelo, numeroSerie?, descripcion, fecha_recepcion'
'- ordenes: id, codigo, equipoId, estado, creada, actualizada'
'- eventos: id, ordenId, tipo(''nota''|''prueba''|''cambio_estado''), texto, fecha'
'- piezas: id, ordenId, nombre, cantidad, coste, estado(''pendiente''|''pedido''|''recibido''|''instalado'')'
'- adjuntos (v2): id, ordenId, nombre, tipo, tam, fecha, blob'
''
'Estados: recepcion | diagnostico | reparacion | listo | entregado.'
''
'## Flujos'
'1) Registro → crea 1 orden por equipo.'
'2) Órdenes → buscar/filtrar y abrir.'
'3) Reparación → notas, piezas, adjuntos, costes, edición, estados.'
'4) Exportar/Imprimir → CSV/JSON o impresión.'
''
'## Exportar / Importar'
'- CSV desde Órdenes.'
'- JSON completo desde Reparación.'
'- Importar JSON en Órdenes (sobrescribe tablas).'
''
'## Despliegue (GitHub Pages)'
'1) Ajusta `base` en `vite.config.ts` a ''/NOMBRE_REPO/''.'
'2) `npm run build`'
'3) Publica `dist/` (p. ej., rama `gh-pages`).'
''
'## Troubleshooting'
'- Acentos: usar UTF-8 o escapes `\uXXXX`.'
'- Tailwind 4: `@tailwindcss/postcss` en `postcss.config.js`.'
'- Cache Vite: borrar `node_modules/.vite`.'
''
'## Licencia'
'Privado. Uso interno BricoFrank.'
)
Set-Content README.md -Value $readme -Encoding utf8

# ------- CHANGELOG.md -------
$changelog = @(
'# Historial de cambios'
''
'## [Unreleased]'
'- Inventario de piezas con stock y proveedores.'
'- Hoja de recepción con QR.'
'- Exportar a PDF del presupuesto.'
''
'## v0.6.0 — Plantillas y presets'
'- Plantillas rápidas de notas y diagnóstico en Timeline.'
'- Presets de tarifa (20/25/30/35 €/h) y atajos de horas (0.5/1/2). Persistencia en localStorage.'
'- Mantiene cálculo sin IVA.'
''
'## v0.5.0 — Adjuntos y filtros'
'- Adjuntos en Reparación: subir, previsualizar, descargar y borrar (Dexie v2 con `adjuntos`).'
'- Filtros en Órdenes: estado, fechas y ordenación.'
'- Botón Imprimir con estilos de impresión.'
''
'## v0.4.0 — Exportación/Importación'
'- Exportar CSV en Órdenes.'
'- Importar JSON para restaurar backups.'
''
'## v0.3.0 — Registro múltiple'
'- Registro admite varios equipos por cliente.'
'- Nueva categoría Baterías.'
''
'## v0.2.0 — Listado y presupuesto'
'- Listado de Órdenes con búsqueda y navegación.'
'- Cálculo de Presupuesto sin IVA.'
''
'## v0.1.0 — Base'
'- Vite + React + TypeScript + Tailwind.'
'- Pestañas: Registro, Órdenes, Presupuesto, Reparación.'
'- Dexie: clientes, equipos, órdenes, eventos y piezas.'
)
Set-Content CHANGELOG.md -Value $changelog -Encoding utf8

Write-Host 'README.md y CHANGELOG.md generados.'
